// Copyright 2021 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DeepSpeedJobLister helps list DeepSpeedJobs.
// All objects returned here must be treated as read-only.
type DeepSpeedJobLister interface {
	// List lists all DeepSpeedJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DeepSpeedJob, err error)
	// DeepSpeedJobs returns an object that can list and get DeepSpeedJobs.
	DeepSpeedJobs(namespace string) DeepSpeedJobNamespaceLister
	DeepSpeedJobListerExpansion
}

// deepSpeedJobLister implements the DeepSpeedJobLister interface.
type deepSpeedJobLister struct {
	indexer cache.Indexer
}

// NewDeepSpeedJobLister returns a new DeepSpeedJobLister.
func NewDeepSpeedJobLister(indexer cache.Indexer) DeepSpeedJobLister {
	return &deepSpeedJobLister{indexer: indexer}
}

// List lists all DeepSpeedJobs in the indexer.
func (s *deepSpeedJobLister) List(selector labels.Selector) (ret []*v1.DeepSpeedJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DeepSpeedJob))
	})
	return ret, err
}

// DeepSpeedJobs returns an object that can list and get DeepSpeedJobs.
func (s *deepSpeedJobLister) DeepSpeedJobs(namespace string) DeepSpeedJobNamespaceLister {
	return deepSpeedJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// DeepSpeedJobNamespaceLister helps list and get DeepSpeedJobs.
// All objects returned here must be treated as read-only.
type DeepSpeedJobNamespaceLister interface {
	// List lists all DeepSpeedJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DeepSpeedJob, err error)
	// Get retrieves the DeepSpeedJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DeepSpeedJob, error)
	DeepSpeedJobNamespaceListerExpansion
}

// deepSpeedJobNamespaceLister implements the DeepSpeedJobNamespaceLister
// interface.
type deepSpeedJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all DeepSpeedJobs in the indexer for a given namespace.
func (s deepSpeedJobNamespaceLister) List(selector labels.Selector) (ret []*v1.DeepSpeedJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DeepSpeedJob))
	})
	return ret, err
}

// Get retrieves the DeepSpeedJob from the indexer for a given namespace and name.
func (s deepSpeedJobNamespaceLister) Get(name string) (*v1.DeepSpeedJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("deepspeedjob"), name)
	}
	return obj.(*v1.DeepSpeedJob), nil
}
